filter:
    excluded_paths:
        - './Examples/*'
build:
    environment:
          php:
            version: '7.0'
            ini:
                'zend_extension': 'xdebug.so'
    nodes:
        analysis:
            tests:
                override:
                    - 'php-scrutinizer-run'
                    -
                        command: make test_coverage
                        coverage:
                            file: 'tests/_output/coverage.xml'
                            format: 'clover'
        tests: true
        
checks:
    php:
        code_rating: true
        duplication: true
        fix_php_opening_tag: true
        remove_php_closing_tag: true
        no_mixed_inline_html: true
        require_braces_around_control_structures: true
        psr2_control_structure_declaration: true
        avoid_superglobals: false
        security_vulnerabilities: true
        no_exit: true
filter: {  }
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

tools:
    php_code_coverage: true
    php_analyzer: true
    php_pdepend:
        excluded_dirs:
            - vendor
            - tests
            - Examples